[package]
name = "pixelscript"
version = "0.6.6"
edition = "2024"
license = "Apache-2.0"
authors = ["Jordan Castro jordan@grupojvm.com"]
description = "Multi language scripting runtime"
repository = "https://github.com/jordan-castro/pixelscript"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[[bin]]
name = "pxs"
path = "src/main.rs"

[dependencies]
etffi = "0.1.3"

[build-dependencies]
cbindgen = "0.29.2"
cc = "1.2.52"
bindgen = "0.72.1"

[features]
# Default includes all languages and cores.
default = ["lua", "python", "js", "include-core", "js_commonjs"]
# Include LUA scripting.
lua = []
# Include Python scripting. Via pocketpy
python = []
# luajit uses the same lua engine but with JIT flags
luajit = []
js = []

# JS specific to add or not to add CommonJS `require`
js_commonjs = []

# Core libs
# Include all core libs (toggled by default)
include-core = [
    "pxs_json",
    "pxs_mem",
    "pxs_os",
    "pxs_pxs",
    "pxs_fs",
    "pxs_shell",
    "pxs_http",
    "pxs_zip"
]
pxs_json = []
pxs_mem = []

# Compile pixel script to debug in a "release" enviroment
pxs-debug = []

testing = []

# pxs_core
pxs_pxs = []
pxs_os = []
pxs_fs = []
pxs_shell = []
pxs_http = []
pxs_zip = []

[profile.release]
opt-level = "z"
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
incremental = false
